import Knex from "knex";
import { RedisClient } from "redis";
import Root from "../base/Root";
import { ISensitiveConfigRawJSONDataType, IConfigRawJSONDataType } from "../config";
import { SEOGenerator } from "./seo/generator";
export declare class GlobalManager {
    private root;
    private knex;
    private globalCache;
    private redisPub;
    private idefNeedsMantenience;
    private modNeedsMantenience;
    private serverData;
    private serverDataLastUpdated;
    private currencyLayer;
    private sensitiveConfig;
    private config;
    private seoGenerator;
    constructor(root: Root, knex: Knex, globalCache: RedisClient, redisPub: RedisClient, config: IConfigRawJSONDataType, sensitiveConfig: ISensitiveConfigRawJSONDataType);
    setSEOGenerator(seoGenerator: SEOGenerator): void;
    private addAdminUserIfMissing;
    private processModule;
    private processIdef;
    run(): void;
    private runOnce;
    private runForModule;
    private runForIdef;
    private runFor;
    private calculateServerData;
    private informNewServerData;
}
