import { IAppDataType } from "../../../server";
import { IGraphQLIdefResolverArgs, FGraphQLIdefResolverType, FGraphQLModResolverType } from "../../../base/Root/gql";
import Module from "../../../base/Root/Module";
import ItemDefinition from "../../../base/Root/Module/ItemDefinition";
import { IGQLSearchRecordsContainer, IGQLSearchResultsContainer } from "../../../gql-querier";
export declare function searchModuleTraditional(appData: IAppDataType, resolverArgs: IGraphQLIdefResolverArgs, mod: Module): Promise<IGQLSearchRecordsContainer | IGQLSearchResultsContainer>;
export declare function searchModule(appData: IAppDataType, resolverArgs: IGraphQLIdefResolverArgs, mod: Module, traditional?: boolean): Promise<IGQLSearchRecordsContainer | IGQLSearchResultsContainer>;
export declare function searchItemDefinitionTraditional(appData: IAppDataType, resolverArgs: IGraphQLIdefResolverArgs, itemDefinition: ItemDefinition): Promise<IGQLSearchRecordsContainer | IGQLSearchResultsContainer>;
export declare function searchItemDefinition(appData: IAppDataType, resolverArgs: IGraphQLIdefResolverArgs, resolverItemDefinition: ItemDefinition, traditional?: boolean): Promise<IGQLSearchRecordsContainer | IGQLSearchResultsContainer>;
export declare function searchItemDefinitionFn(appData: IAppDataType): FGraphQLIdefResolverType;
export declare function searchModuleFn(appData: IAppDataType): FGraphQLModResolverType;
export declare function searchItemDefinitionTraditionalFn(appData: IAppDataType): FGraphQLIdefResolverType;
export declare function searchModuleTraditionalFn(appData: IAppDataType): FGraphQLModResolverType;
