export default {
  "@babel/core": "^7.7.7",
  "@babel/plugin-proposal-class-properties": "^7.7.4",
  "@babel/plugin-transform-regenerator": "^7.7.5",
  "@babel/preset-env": "^7.7.7",
  "@babel/preset-react": "^7.7.4",
  "@babel/preset-typescript": "^7.7.7",
  "babel-core": "^6.26.3",
  "babel-loader": "^8.0.6",
  "babel-preset-env": "^1.7.0",
  "babel-preset-react": "^6.24.1",
  "css-loader": "^2.1.1",
  "mini-css-extract-plugin": "^0.5.0",
  "node-sass": "^4.13.1",
  "null-loader": "^0.1.1",
  "sass-loader": "^7.3.1",
  "source-map-loader": "^0.2.4",
  "tslint": "^5.20.1",
  "tslint-react": "^3.6.0",
  "typescript": "^3.7.4",
  "url-loader": "^1.1.2",
  "webpack": "^4.41.4",
  "webpack-bundle-analyzer": "^3.6.0",
  "webpack-cli": "^3.3.10",
  "worker-injector-generator-plugin": "^1.0.1",
};
