declare const _default: {
    "@types/react": string;
    "@types/react-dom": string;
    react: string;
    "react-dom": string;
    "deep-equal": string;
    "@babel/core": string;
    "@babel/plugin-proposal-class-properties": string;
    "@babel/plugin-transform-regenerator": string;
    "@babel/preset-env": string;
    "@babel/preset-react": string;
    "@babel/preset-typescript": string;
    "babel-core": string;
    "babel-loader": string;
    "babel-preset-env": string;
    "babel-preset-react": string;
    "css-loader": string;
    "mini-css-extract-plugin": string;
    "node-sass": string;
    "null-loader": string;
    "sass-loader": string;
    "source-map-loader": string;
    "url-loader": string;
    webpack: string;
    "webpack-cli": string;
    "worker-injector-generator-plugin": string;
    typescript: string;
    tslint: string;
    "tslint-react": string;
    "webpack-bundle-analyzer": string;
};
export default _default;
